# Generated by Django 5.1.6 on 2025-02-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_remove_fantasyroster_game_stats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyteam',
            name='total_stats',
            field=models.JSONField(default=dict),
        ),
    ]
