# Generated by Django 5.1.6 on 2025-03-02 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0008_fantasyroster_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
