# Generated by Django 5.1.6 on 2025-03-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0010_remove_fantasyteam_total_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyroster',
            name='stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='stats',
            field=models.JSONField(default=dict),
        ),
    ]
