# Generated by Django 5.1.6 on 2025-03-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0011_fantasyroster_stats_fantasyteam_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='player_images/'),
        ),
    ]
