# Generated by Django 5.1.6 on 2025-03-04 00:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0012_player_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasyroster',
            name='active',
        ),
        migrations.AddField(
            model_name='player',
            name='eligible_positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'), ('C', 'Catcher'), ('CI', 'Corner Infield'), ('MI', 'Middle Infield'), ('IF', 'Infield'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('OF', 'Outfield'), ('UTIL', 'Utility'), ('SP', 'Starting Pitcher'), ('RP', 'Relief Pitcher'), ('P', 'Pitcher'), ('IL', 'Injured List')], max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='fantasyroster',
            name='position',
            field=models.CharField(choices=[('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'), ('C', 'Catcher'), ('CI', 'Corner Infield'), ('MI', 'Middle Infield'), ('IF', 'Infield'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('OF', 'Outfield'), ('UTIL', 'Utility'), ('SP', 'Starting Pitcher'), ('RP', 'Relief Pitcher'), ('P', 'Pitcher'), ('IL', 'Injured List')], max_length=4),
        ),
    ]
