# Generated by Django 5.1.6 on 2025-03-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0013_remove_fantasyroster_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fantasyteam',
            old_name='stats',
            new_name='total_stats',
        ),
    ]
