# Generated by Django 5.1.6 on 2025-03-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0014_rename_stats_fantasyteam_total_stats'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fantasyroster',
            constraint=models.UniqueConstraint(condition=models.Q(('fantasy_team__isnull', False)), fields=('fantasy_team', 'player'), name='unique_player_per_team'),
        ),
    ]
