# Generated by Django 5.1.6 on 2025-03-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0015_fantasyroster_unique_player_per_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fantasyleague',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
