# Generated by Django 5.1.6 on 2025-03-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0016_fantasyleague_public_fantasyleague_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='scoring_system',
            field=models.CharField(choices=[('ROT', 'Rotisserie')], default='ROT', max_length=20),
        ),
    ]
